### ISSUE TITLE
Using separate emails for creation and verification

### ISSUE THREAD

**Issue by febs** [Noctem/MonoGen#3]
Hello, would it be possible to use a domain (as zoho.eu) for the account creation and another (like: gmail) for their verification? Of course the email received by zoho.eu would be forwarded to the gmail account.

Also, by trying to use gmail only:
`sudo monogen -r 7231789289241242467244 -e address@gmail.com   -av True -gp googlepass`

I get a syntax error:
`monogen: error: unrecognized arguments: True`

Thank you

**Comment by ventapokimos** [comment]
@febs You can specify the google account using -gm username@gmail.com -gp password.


But this cause an error for me.
Processing mailbox...
Generic Exception: Traceback (most recent call last):
  File "c:\users\mark_\appdata\local\programs\python\python36\lib\site-packages\monogen\console.py", line 190, in entry
    email_verify(args.googlemail, args.googlepass)
  File "c:\users\mark_\appdata\local\programs\python\python36\lib\site-packages\monogen\gmailv.py", line 53, in email_verify
    proc_mail(M)
  File "c:\users\mark_\appdata\local\programs\python\python36\lib\site-packages\monogen\gmailv.py", line 22, in proc_mail
    if subjmsg.find("Trainer_Club_Activation") != -1:
TypeError: a bytes-like object is required, not 'str'`
